version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: workshare-mongo
    ports:
      - "27017:27017"
    volumes:
      - workshare_mongo_data:/data/db

volumes:
  workshare_mongo_data:
